"""initial database migration

Revision ID: e6234d085280
Revises: 5583a61cd4a7
Create Date: 2021-02-16 09:47:01.796111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6234d085280'
down_revision = '5583a61cd4a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dbo.tb_app_secret_key',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_name', sa.String(length=255), nullable=False),
    sa.Column('create_secret_in', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dbo.tb_app_secret_key')
    # ### end Alembic commands ###
